FactoryBot.create(:user, :admin)
FactoryBot.create(:user, :with_workspaces)
FactoryBot.create(:user, :with_workspaces, :with_projects)
FactoryBot.create(:user, :with_workspaces, :with_projects, :comments_for_projects)
FactoryBot.create(:user, :with_workspaces, :with_projects, :comments_for_projects, :with_tasks)
FactoryBot.create(:user, :with_workspaces, :with_projects, :comments_for_projects, :with_tasks, :comments_for_tasks)
FactoryBot.create(:user, :with_workspaces, :with_projects, :comments_for_projects, :with_tasks, :comments_for_tasks, :watchers)